# Propriedades atualizadas conforme documentação
# https://docs.spring.io/spring-boot/docs/3.1.2/reference/html/application-properties.html#appendix.application-properties

spring:
  application:
    name: api-cloud-commerce
  profiles:
    active: local
  datasource:
    username: local
    password: local
    url: jdbc:postgresql://localhost:5432/cloud-commerce-db
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

server:
  port: 4000
  servlet:
    context-path: /api
