spring:
  application:
    name: api-cloud-commerce
  config:
    activate:
      on-profile: prod
  datasource:
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    url: jdbc:postgresql://${PROD_DB_HOST}/${PROD_DB_DATABASE}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

server:
  servlet:
    context-path: /api
